package mjml

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"maps"
	"math/rand/v2"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"runtime/debug"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"
)

// TestDifferential compares gomjml with MJML 4.16.1 over the differential corpus with
// compareWithReference, and each case's defect clusters with its record in
// testdata/differential/<source>.json. Sources without committed goldens are checked by digest
// only; scripts/differential.sh renders their references. See "Differential testing" in the
// README.
func TestDifferential(t *testing.T) {
	if *diffCaseName != "" {
		showCase(t, *diffCaseName)
		return
	}
	if *diffManifest != "" {
		writeManifest(t, *diffManifest)
		return
	}

	var results map[string]reference
	if *diffResults != "" {
		var err error
		if results, err = readResults(*diffResults); err != nil {
			t.Fatalf("reading reference results: %v", err)
		}
	} else if *diffUpdate {
		t.Fatal("-diff.update needs -diff.results; run scripts/differential.sh")
	}

	clusters, err := readKnownClusters()
	if err != nil {
		t.Fatal(err)
	}
	run := &differentialRun{clusters: clusters, results: results}
	for _, source := range differentialSources {
		t.Run(source.name, func(t *testing.T) { run.source(t, source) })
	}

	if results == nil {
		return
	}
	run.assignNewClusters()
	if *diffUpdate {
		if err := run.writeRecords(); err != nil {
			t.Fatal(err)
		}
	}
	report := run.report()
	if err := writeReport(*diffReport, report); err != nil {
		t.Fatal(err)
	}
	t.Logf("report written to %s", *diffReport)
	for _, cluster := range run.clusters {
		if cluster.Reason == "" && run.clusterCases[cluster.ID] > 0 {
			t.Errorf("cluster %s has no reason in known-clusters.json; triage it (signatures: %s)",
				cluster.ID, strings.Join(cluster.Signatures, "; "))
		}
	}
	if run.complete {
		for _, cluster := range run.clusters {
			if run.clusterCases[cluster.ID] == 0 {
				t.Errorf("known cluster %s matches no case; remove it from known-clusters.json", cluster.ID)
			}
		}
	}
}

var (
	diffResults  = flag.String("diff.results", "", "reference results from testdata/reference/batch.mjs; compares every source with MJML")
	diffUpdate   = flag.Bool("diff.update", false, "with -diff.results, rewrite the differential records and the mrml goldens")
	diffReport   = flag.String("diff.report", filepath.Join(differentialCache, "report"), "with -diff.results, where to write report.md and report.json")
	diffManifest = flag.String("diff.manifest", "", "write the cases batch.mjs renders to this JSONL file, and stop")
	diffCaseName = flag.String("diff.case", "", "print the differences, signatures and unified diff of one case, and stop")
	diffTimeout  = flag.Duration("diff.timeout", 10*time.Second, "how long one render may take before it counts as a hang")
	crashSeeds   = flag.Int("diff.crash-seeds", 1000, "how many extra fuzzer seeds TestDifferentialCrashes renders")
)

var errSourceUnavailable = errors.New("source unavailable")

type diffSource struct {
	name    string
	licence string
	// goldens is the directory of the committed reference HTML, if the source commits it.
	goldens string
	// rendered says whether batch.mjs renders the source; testdata has render.mjs instead.
	rendered bool
	cases    func() ([]diffCase, error)
}

var differentialSources = []diffSource{
	{name: "testdata", licence: "gomjml's own fixtures (MIT)", goldens: "testdata", cases: testdataCases},
	{name: "mrml", licence: "MIT, © Jérémie Drouet (github.com/jdrouet/mrml)", goldens: filepath.Join(differentialDir, "mrml"), rendered: true, cases: func() ([]diffCase, error) {
		return directoryCases("mrml", filepath.Join(differentialDir, "mrml"))
	}},
	{name: "email-templates", licence: "no licence stated; fetched, not committed", rendered: true, cases: func() ([]diffCase, error) {
		return directoryCases("email-templates", filepath.Join(differentialCache, "email-templates", "templates"))
	}},
	{name: "generated", licence: "generated by this harness", rendered: true, cases: generatedCases},
	{name: "fuzz", licence: "generated by this harness", rendered: true, cases: func() ([]diffCase, error) { return fuzzCases(), nil }},
}

// reference is MJML's result for a case, as batch.mjs writes it.
type reference struct {
	Name     string        `json:"name"`
	HTML     string        `json:"html,omitempty"`
	Error    string        `json:"error,omitempty"`
	Warnings []ErrorDetail `json:"warnings,omitempty"`
}

func readResults(path string) (map[string]reference, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	results := map[string]reference{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1<<20), 64<<20)
	for scanner.Scan() {
		var r reference
		if err := json.Unmarshal(scanner.Bytes(), &r); err != nil {
			return nil, err
		}
		results[r.Name] = r
	}
	return results, scanner.Err()
}

// goldenReference reads a committed golden: <name>.html, or <name>.error when MJML rejects it.
func goldenReference(dir, name string) (reference, bool) {
	base := filepath.Join(dir, name[strings.Index(name, "/")+1:])
	if content, err := os.ReadFile(base + ".error"); err == nil {
		return reference{Name: name, Error: strings.TrimSpace(string(content))}, true
	}
	if content, err := os.ReadFile(base + ".html"); err == nil {
		return reference{Name: name, HTML: string(content)}, true
	}
	return reference{}, false
}

// renderGuarded renders input with gomjml, turning a panic or a render that outlives the
// timeout into crash, so that one bad input cannot stop the harness. A hung render's goroutine
// is left running.
func renderGuarded(input string, timeout time.Duration, opts ...RenderOption) (html string, err error, crash string) {
	type outcome struct {
		html  string
		err   error
		crash string
	}
	done := make(chan outcome, 1)
	go func() {
		defer func() {
			if recovered := recover(); recovered != nil {
				done <- outcome{crash: fmt.Sprintf("panic: %v\n%s", recovered, debug.Stack())}
			}
		}()
		html, err := Render(input, opts...)
		done <- outcome{html: html, err: err}
	}()
	select {
	case o := <-done:
		return o.html, o.err, o.crash
	case <-time.After(timeout):
		return "", nil, fmt.Sprintf("hang: no result after %s", timeout)
	}
}

var goroutineFrame = regexp.MustCompile(`(?m)^(github\.com/preslavrachev/gomjml/[^\s(]+)\(`)

// crashSignature names a crash by its kind, message and innermost gomjml frame.
func crashSignature(crash string) string {
	if strings.HasPrefix(crash, "hang") {
		return "document crash-hang render"
	}
	message, _, _ := strings.Cut(strings.TrimPrefix(crash, "panic: "), "\n")
	frame := ""
	for _, match := range goroutineFrame.FindAllStringSubmatch(crash, -1) {
		if !strings.Contains(match[1], "mjml.renderGuarded") && !strings.Contains(match[1], "_test") {
			frame = match[1]
			break
		}
	}
	return fmt.Sprintf("document crash-panic %s at %s", digits.ReplaceAllString(message, "N"), frame)
}

func inputHash(c diffCase) string {
	sum := sha256.Sum256([]byte(c.Pkg + "\x00" + c.MJML))
	return hex.EncodeToString(sum[:6])
}

// outputDigest identifies an output the way the comparison sees it, after normalisation.
func outputDigest(html string) string {
	return digestLines(canonicalLines(normalizeForComparison(html)))
}

func referenceDigest(r reference) string {
	if r.Error != "" {
		return "error"
	}
	return outputDigest(r.HTML)
}

var debugTagPattern = regexp.MustCompile(` data-mj-debug-[a-z-]+="true"`)

// caseResult is what evaluating one case found.
type caseResult struct {
	name, input    string
	gomjml         string // output digest, "error" or "crash"
	reference      string // "" when no reference is available
	differences    []string
	signatures     []string
	validation     []string // gomjml validation errors MJML does not report
	byteIdentical  bool
	crash          string
	referenceHTML  string
	gomjmlHTML     string
	referenceError string
	gomjmlError    string
}

func (r *caseResult) failing() bool { return len(r.signatures) > 0 }

// evaluate renders c with gomjml and, when ref is not nil, compares the result with it.
func evaluate(c diffCase, ref *reference) *caseResult {
	result := &caseResult{name: c.Name, input: inputHash(c)}
	html, err, crash := renderGuarded(c.MJML, *diffTimeout)
	var details []ErrorDetail
	var mjmlErr Error
	switch {
	case crash != "":
		result.crash = crash
		result.gomjml = "crash"
	case err != nil && html != "" && errors.As(err, &mjmlErr) && len(mjmlErr.Details) > 0:
		// Validation errors: gomjml still renders, as MJML does in its default soft mode.
		details = mjmlErr.Details
		result.gomjml = outputDigest(html)
	case err != nil:
		result.gomjml = "error"
		result.gomjmlError = err.Error()
	default:
		result.gomjml = outputDigest(html)
	}
	result.gomjmlHTML = html
	if ref == nil {
		return result
	}

	result.reference = referenceDigest(*ref)
	result.referenceHTML = ref.HTML
	result.referenceError = ref.Error
	switch {
	case crash != "":
		result.signatures = []string{crashSignature(crash)}
	case ref.Error != "" && result.gomjml == "error":
		// Both reject the document.
	case ref.Error != "":
		result.differences = []string{fmt.Sprintf("MJML rejects this input (%s) but gomjml rendered it", ref.Error)}
		result.signatures = []string{"document mjml-rejects gomjml-renders"}
	case result.gomjml == "error":
		message, _, _ := strings.Cut(result.gomjmlError, "\n")
		result.differences = []string{"gomjml failed to render: " + result.gomjmlError}
		result.signatures = []string{"document gomjml-rejects " + quotedValues.ReplaceAllString(digits.ReplaceAllString(message, "N"), `"…"`)}
	default:
		result.byteIdentical = maskGeneratedIDs(ref.HTML) == maskGeneratedIDs(html)
		if result.byteIdentical {
			break
		}
		result.differences, _ = compareWithReference(c.Name, ref.HTML, html)
		if len(result.differences) == 0 {
			break
		}
		debugHTML, _, _ := renderGuarded(c.MJML, *diffTimeout, WithDebugTags(true))
		if maskGeneratedIDs(debugTagPattern.ReplaceAllString(debugHTML, "")) != maskGeneratedIDs(html) {
			// Debug tags must only add attributes; otherwise name no components.
			debugHTML = html
		}
		result.signatures = differenceSignatures(ref.HTML, debugHTML)
		if len(result.signatures) == 0 {
			for _, difference := range result.differences {
				header, _, _ := strings.Cut(ansiEscape.ReplaceAllString(difference, ""), "\n")
				result.signatures = append(result.signatures, "document unclassified "+strings.TrimSuffix(strings.TrimSpace(header), ":"))
			}
			slices.Sort(result.signatures)
			result.signatures = slices.Compact(result.signatures)
		}
	}
	for _, detail := range details {
		if !slices.ContainsFunc(ref.Warnings, func(w ErrorDetail) bool { return w.Line == detail.Line && w.TagName == detail.TagName }) {
			result.validation = append(result.validation, fmt.Sprintf("<%s> %s", detail.TagName, quotedValues.ReplaceAllString(detail.Message, `"…"`)))
		}
	}
	return result
}

var quotedValues = regexp.MustCompile(`"[^"]*"`)

// caseRecord is one case of testdata/differential/<source>.json.
type caseRecord struct {
	Name      string   `json:"name"`
	Input     string   `json:"input"`
	Reference string   `json:"reference"`
	Gomjml    string   `json:"gomjml"`
	Clusters  []string `json:"clusters,omitempty"`
}

func recordPath(source string) string { return filepath.Join(differentialDir, source+".json") }

func readRecords(source string) (map[string]caseRecord, error) {
	content, err := os.ReadFile(recordPath(source))
	if errors.Is(err, os.ErrNotExist) {
		return map[string]caseRecord{}, nil
	}
	if err != nil {
		return nil, err
	}
	var file struct {
		Cases []caseRecord `json:"cases"`
	}
	if err := json.Unmarshal(content, &file); err != nil {
		return nil, fmt.Errorf("%s: %w", recordPath(source), err)
	}
	records := make(map[string]caseRecord, len(file.Cases))
	for _, record := range file.Cases {
		records[record.Name] = record
	}
	return records, nil
}

// writeRecordFile writes one case per line, so that a change to a case is a one-line diff.
func writeRecordFile(source string, records []caseRecord) error {
	slices.SortFunc(records, func(a, b caseRecord) int { return strings.Compare(a.Name, b.Name) })
	var b strings.Builder
	fmt.Fprintf(&b, "{\n  \"source\": %q,\n  \"reference\": \"mjml 4.16.1\",\n  \"cases\": [\n", source)
	for i, record := range records {
		line, err := json.Marshal(record)
		if err != nil {
			return err
		}
		b.WriteString("    ")
		b.Write(line)
		if i < len(records)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("  ]\n}\n")
	return os.WriteFile(recordPath(source), []byte(b.String()), 0o644)
}

// knownCluster is a defect: the difference signatures it shows up as, and why.
type knownCluster struct {
	ID         string   `json:"id"`
	Reason     string   `json:"reason"`
	Signatures []string `json:"signatures"`
}

var knownClustersPath = filepath.Join(differentialDir, "known-clusters.json")

func readKnownClusters() ([]*knownCluster, error) {
	content, err := os.ReadFile(knownClustersPath)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var clusters []*knownCluster
	if err := json.Unmarshal(content, &clusters); err != nil {
		return nil, fmt.Errorf("%s: %w", knownClustersPath, err)
	}
	seen := map[string]string{}
	for _, cluster := range clusters {
		for _, signature := range cluster.Signatures {
			if other, dup := seen[signature]; dup {
				return nil, fmt.Errorf("%s: signature %q is in both %s and %s", knownClustersPath, signature, other, cluster.ID)
			}
			seen[signature] = cluster.ID
		}
	}
	return clusters, nil
}

func writeKnownClusters(clusters []*knownCluster) error {
	content, err := json.MarshalIndent(clusters, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(knownClustersPath, append(content, '\n'), 0o644)
}

// differentialRun collects the results of every source for the records and the report.
type differentialRun struct {
	clusters     []*knownCluster
	results      map[string]reference // nil without -diff.results
	mu           sync.Mutex
	sources      []sourceRun
	clusterCases map[string]int
	complete     bool
}

type sourceRun struct {
	source  diffSource
	skipped string
	results []*caseResult
}

func (run *differentialRun) clusterOf(signature string) string {
	for _, cluster := range run.clusters {
		if slices.Contains(cluster.Signatures, signature) {
			return cluster.ID
		}
	}
	return ""
}

// clustersOf lists the known clusters a case's signatures belong to, and the signatures no
// cluster knows.
func (run *differentialRun) clustersOf(result *caseResult) (clusters, unknown []string) {
	for _, signature := range result.signatures {
		if id := run.clusterOf(signature); id != "" {
			clusters = append(clusters, id)
		} else {
			unknown = append(unknown, signature)
		}
	}
	slices.Sort(clusters)
	return slices.Compact(clusters), unknown
}

func (run *differentialRun) source(t *testing.T, source diffSource) {
	cases, err := source.cases()
	if errors.Is(err, errSourceUnavailable) {
		run.mu.Lock()
		run.sources = append(run.sources, sourceRun{source: source, skipped: "not fetched"})
		run.mu.Unlock()
		t.Skipf("%s is not fetched; scripts/differential.sh fetches it", source.name)
	}
	if err != nil {
		t.Fatal(err)
	}
	records, err := readRecords(source.name)
	if err != nil {
		t.Fatal(err)
	}
	names := map[string]bool{}
	for _, c := range cases {
		names[c.Name] = true
	}
	if !*diffUpdate {
		for name := range records {
			if !names[name] {
				t.Errorf("%s is recorded in %s but is no longer in the corpus; run scripts/differential.sh", name, recordPath(source.name))
			}
		}
	}

	results := make([]*caseResult, len(cases))
	var wg sync.WaitGroup
	work := make(chan int)
	for range runtime.GOMAXPROCS(0) {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := range work {
				c := cases[i]
				var ref *reference
				if run.results != nil && source.rendered {
					if r, ok := run.results[c.Name]; ok {
						ref = &r
					}
				} else if source.goldens != "" {
					if r, ok := goldenReference(source.goldens, c.Name); ok {
						ref = &r
					}
				}
				result := evaluate(c, ref)
				// Only a failing case's outputs are shown in the report, and goldens written.
				if !result.failing() && !(*diffUpdate && source.goldens != "") {
					result.referenceHTML, result.gomjmlHTML = "", ""
				}
				results[i] = result
			}
		}()
	}
	for i := range cases {
		work <- i
	}
	close(work)
	wg.Wait()

	run.mu.Lock()
	run.sources = append(run.sources, sourceRun{source: source, results: results})
	run.mu.Unlock()

	failures := 0
	for _, result := range results {
		if message := run.check(result, records); message != "" {
			if failures++; failures <= 40 {
				t.Errorf("%s: %s", result.name, message)
			}
		}
	}
	if failures > 40 {
		t.Errorf("... and %d more failing cases", failures-40)
	}
}

// check compares a case's result with its record, returning why they disagree.
func (run *differentialRun) check(result *caseResult, records map[string]caseRecord) string {
	if *diffUpdate {
		return ""
	}
	record, ok := records[result.name]
	switch {
	case !ok:
		return "not recorded; run scripts/differential.sh"
	case record.Input != result.input:
		return "its input changed since it was compared with MJML; run scripts/differential.sh"
	}
	if result.reference == "" {
		if result.gomjml == record.Gomjml {
			return ""
		}
		if result.crash != "" {
			return "gomjml crashed: " + result.crash
		}
		if len(record.Clusters) == 0 {
			return "gomjml's output changed since it was compared with MJML; run scripts/differential.sh to compare it again"
		}
		if result.gomjml == record.Reference {
			return "gomjml's output now has MJML's digest; run scripts/differential.sh to record the fix"
		}
		return fmt.Sprintf("gomjml's output changed since it was compared with MJML (known clusters %s); run scripts/differential.sh",
			strings.Join(record.Clusters, ", "))
	}

	if result.reference != record.Reference {
		return "the reference output changed since it was recorded; run scripts/differential.sh"
	}
	clusters, unknown := run.clustersOf(result)
	if len(unknown) > 0 {
		return fmt.Sprintf("differs from MJML in ways no known cluster covers:\n  %s\n%s",
			strings.Join(unknown, "\n  "), strings.Join(result.differences, "\n\n"))
	}
	if !slices.Equal(clusters, record.Clusters) {
		if len(clusters) == 0 {
			return fmt.Sprintf("now matches MJML; run scripts/differential.sh to drop its clusters %s", strings.Join(record.Clusters, ", "))
		}
		return fmt.Sprintf("shows clusters %s but %s are recorded; run scripts/differential.sh after triage\n%s",
			strings.Join(clusters, ", "), strings.Join(record.Clusters, ", "), strings.Join(result.differences, "\n\n"))
	}
	if len(clusters) > 0 && result.gomjml != record.Gomjml {
		return fmt.Sprintf("still shows clusters %s, but its output changed; run scripts/differential.sh after checking the differences\n%s",
			strings.Join(clusters, ", "), strings.Join(result.differences, "\n\n"))
	}
	return ""
}

// assignNewClusters groups the signatures no known cluster covers into new clusters without a
// reason. Two signatures share a cluster when they are the same family (signatureFamily), or when
// they show up together in at least two cases and in nearly the same cases (the Jaccard index of
// their case sets is at least 0.6), or when they are what one generated case, or one case alone,
// shows.
func (run *differentialRun) assignNewClusters() {
	parent := map[string]string{}
	var find func(string) string
	find = func(x string) string {
		if parent[x] != x {
			parent[x] = find(parent[x])
		}
		return parent[x]
	}
	union := func(a, b string) { parent[find(a)] = find(b) }

	count := map[string]int{}
	together := map[[2]string]int{}
	for _, source := range run.sources {
		for _, result := range source.results {
			_, unknown := run.clustersOf(result)
			for i, a := range unknown {
				if _, ok := parent[a]; !ok {
					parent[a] = a
				}
				count[a]++
				for _, b := range unknown[i+1:] {
					together[[2]string{a, b}]++
				}
			}
		}
	}
	for pair, both := range together {
		// Two signatures of one case prove little; ask for a second case.
		if both >= 2 && float64(both)/float64(count[pair[0]]+count[pair[1]]-both) >= 0.6 {
			union(pair[0], pair[1])
		}
	}
	// Signatures only one case shows are mostly what one structural difference does to the
	// alignment of what follows it, so each case's are one cluster.
	for _, source := range run.sources {
		for _, result := range source.results {
			_, unknown := run.clustersOf(result)
			var single []string
			for _, signature := range unknown {
				if count[signature] == 1 {
					single = append(single, signature)
				}
			}
			for i := 1; i < len(single); i++ {
				union(single[0], single[i])
			}
		}
	}
	// A signature seen only where the generator sets one attribute of one component belongs with
	// the other signatures of that attribute, or, through mj-attributes or mj-class, of that
	// component.
	generatedFamily := map[string]string{}
	for _, source := range run.sources {
		for _, result := range source.results {
			_, unknown := run.clustersOf(result)
			family := generatedCaseFamily(result.name)
			for _, signature := range unknown {
				if previous, seen := generatedFamily[signature]; !seen {
					generatedFamily[signature] = family
				} else if previous != family {
					generatedFamily[signature] = ""
				}
			}
		}
	}
	families := map[string]string{}
	for signature, family := range generatedFamily {
		if family == "" {
			continue
		}
		if first, ok := families[family]; ok {
			union(first, signature)
		} else {
			families[family] = signature
		}
	}
	for signature := range parent {
		// A single case's signatures stay together, not with the family, which they would chain.
		if family := signatureFamily(signature); family != "" && count[signature] > 1 {
			if first, ok := families[family]; ok {
				union(first, signature)
			} else {
				families[family] = signature
			}
		}
	}
	groups := map[string][]string{}
	for signature := range parent {
		groups[find(signature)] = append(groups[find(signature)], signature)
	}
	for _, signatures := range groups {
		slices.Sort(signatures)
		run.clusters = append(run.clusters, &knownCluster{ID: "new-" + digestLines(signatures), Signatures: signatures})
	}
	slices.SortStableFunc(run.clusters, func(a, b *knownCluster) int { return strings.Compare(a.ID, b.ID) })

	run.clusterCases = map[string]int{}
	run.complete = true
	for _, source := range run.sources {
		if source.skipped != "" {
			run.complete = false
		}
		for _, result := range source.results {
			clusters, _ := run.clustersOf(result)
			for _, id := range clusters {
				run.clusterCases[id]++
			}
		}
	}
}

var (
	styleTarget = regexp.MustCompile(`^([\w:.-]+)[{\[]([\w-]+)[}\]]$`)
	sideSuffix  = regexp.MustCompile(`^(padding|margin|border|inner-border)(-(top|right|bottom|left))?(-.*)?$`)
)

// generatedCaseFamily names the attribute a generated attribute case sets, or the component an
// mj-attributes or mj-class case sets defaults for; other cases have no family.
func generatedCaseFamily(name string) string {
	parts := strings.Split(name, "/")
	if len(parts) < 3 || parts[0] != "generated" {
		return ""
	}
	switch parts[1] {
	case "attr":
		attribute, _, _ := strings.Cut(parts[3], "=")
		return "case attr " + parts[2] + " " + attribute
	case "mj-attributes", "mj-class":
		return "case " + parts[1] + " " + parts[2]
	}
	return ""
}

var phrasingElements = map[string]bool{"a": true, "b": true, "i": true, "em": true, "strong": true, "span": true,
	"br": true, "p": true, "u": true, "sup": true, "sub": true, "small": true}

// signatureFamily puts together the signatures of one component and element that are likely one
// defect: the same property or attribute however it differs, in or out of MSO blocks, with the
// sides of padding, margin and border as one, and text and inline elements that move within one
// parent. Other structural and document signatures have no family.
func signatureFamily(signature string) string {
	component, rest, _ := strings.Cut(signature, " ")
	kind, target, _ := strings.Cut(rest, " ")
	switch {
	case kind == "mso-missing" || kind == "mso-extra":
		return component + " mso-structure"
	case kind == "text-changed" || strings.HasPrefix(target, "text in "):
		_, parent, _ := strings.Cut(target, " in ")
		return component + " text " + parent
	case kind == "missing" || kind == "extra":
		element, parent, _ := strings.Cut(strings.TrimPrefix(target, "element "), " in ")
		if phrasingElements[element] {
			return component + " inline content in " + parent
		}
	}
	kind = strings.TrimPrefix(kind, "mso-")
	switch {
	case strings.HasPrefix(kind, "css-"):
		if component != "head" {
			return component + " css"
		}
		// Head rules no component claims: one family per leading selector token.
		selector := target
		if strings.HasPrefix(selector, "@media") {
			if i := strings.LastIndex(selector, ") "); i != -1 {
				selector = selector[i+2:]
			}
		}
		token, _, _ := strings.Cut(selector, " ")
		token, _, _ = strings.Cut(token, "{")
		return "head css " + token
	case strings.HasPrefix(kind, "style-"), strings.HasPrefix(kind, "attr-"):
		match := styleTarget.FindStringSubmatch(target)
		if match == nil {
			return ""
		}
		property := match[2]
		if side := sideSuffix.FindStringSubmatch(property); side != nil {
			property = side[1] + side[4]
		}
		return component + " " + match[1] + " " + property
	}
	return ""
}

func (run *differentialRun) writeRecords() error {
	for _, source := range run.sources {
		if source.skipped != "" {
			continue
		}
		var records []caseRecord
		for _, result := range source.results {
			if result.reference == "" {
				return fmt.Errorf("%s has no reference result; render it with batch.mjs", result.name)
			}
			clusters, _ := run.clustersOf(result)
			records = append(records, caseRecord{result.name, result.input, result.reference, result.gomjml, clusters})
			if source.source.goldens != "" && source.source.rendered {
				if err := writeGolden(source.source.goldens, result); err != nil {
					return err
				}
			}
		}
		if err := writeRecordFile(source.source.name, records); err != nil {
			return err
		}
	}
	if run.complete {
		var used []*knownCluster
		for _, cluster := range run.clusters {
			if run.clusterCases[cluster.ID] > 0 {
				used = append(used, cluster)
			}
		}
		run.clusters = used
	}
	return writeKnownClusters(run.clusters)
}

func writeGolden(dir string, result *caseResult) error {
	base := filepath.Join(dir, result.name[strings.Index(result.name, "/")+1:])
	_ = os.Remove(base + ".html")
	_ = os.Remove(base + ".error")
	if result.referenceError != "" {
		return os.WriteFile(base+".error", []byte(result.referenceError+"\n"), 0o644)
	}
	return os.WriteFile(base+".html", []byte(result.referenceHTML), 0o644)
}

// writeManifest writes every case batch.mjs renders as a JSONL line.
func writeManifest(t *testing.T, path string) {
	file, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	writer := bufio.NewWriter(file)
	count := 0
	for _, source := range differentialSources {
		if !source.rendered {
			continue
		}
		cases, err := source.cases()
		if errors.Is(err, errSourceUnavailable) {
			t.Logf("%s is not fetched; leaving it out", source.name)
			continue
		}
		if err != nil {
			t.Fatal(err)
		}
		for _, c := range cases {
			line, err := json.Marshal(map[string]string{"name": c.Name, "mjml": c.MJML, "pkg": c.Pkg, "filePath": c.FilePath})
			if err != nil {
				t.Fatal(err)
			}
			writer.Write(append(line, '\n'))
			count++
		}
	}
	if err := writer.Flush(); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %d cases to %s", count, path)
}

// showCase prints everything about one case: its signatures, the comparison's differences and
// a unified diff of both outputs, pretty-printed the same way.
func showCase(t *testing.T, name string) {
	source, _, _ := strings.Cut(name, "/")
	i := slices.IndexFunc(differentialSources, func(s diffSource) bool { return s.name == source })
	if i == -1 {
		t.Fatalf("no source %q", source)
	}
	cases, err := differentialSources[i].cases()
	if err != nil {
		t.Fatal(err)
	}
	j := slices.IndexFunc(cases, func(c diffCase) bool { return c.Name == name })
	if j == -1 {
		t.Fatalf("no case %q", name)
	}
	var ref *reference
	resultsPath := *diffResults
	if resultsPath == "" {
		resultsPath = filepath.Join(differentialCache, "results.jsonl")
	}
	if differentialSources[i].goldens != "" && *diffResults == "" {
		if r, ok := goldenReference(differentialSources[i].goldens, name); ok {
			ref = &r
		}
	} else if results, err := readResults(resultsPath); err == nil {
		if r, ok := results[name]; ok {
			ref = &r
		}
	}
	if ref == nil {
		t.Fatalf("no reference output for %s; run scripts/differential.sh", name)
	}
	result := evaluate(cases[j], ref)
	var b strings.Builder
	fmt.Fprintf(&b, "=== %s\n--- input\n%s\n", name, cases[j].MJML)
	if result.byteIdentical {
		b.WriteString("byte-identical to MJML after id masking\n")
	}
	if len(result.signatures) == 0 {
		b.WriteString("semantically equivalent to MJML\n")
	}
	for _, signature := range result.signatures {
		fmt.Fprintf(&b, "signature: %s\n", signature)
	}
	for _, v := range result.validation {
		fmt.Fprintf(&b, "validation (gomjml only): %s\n", v)
	}
	if len(result.differences) > 0 {
		fmt.Fprintf(&b, "--- semantic differences\n%s\n", ansiEscape.ReplaceAllString(strings.Join(result.differences, "\n\n"), ""))
	}
	fmt.Fprintf(&b, "--- unified diff\n%s", caseDiff(result, 3, 0))
	fmt.Println(b.String())
}

// caseDiff is the unified diff of a case's outputs. With maxLines above zero it keeps the
// hunks that mention one of keep's words first, and stops after maxLines lines.
func caseDiff(result *caseResult, context, maxLines int, keep ...string) string {
	from := prettyOutput(result.referenceHTML, result.referenceError)
	to := prettyOutput(result.gomjmlHTML, result.gomjmlError+result.crash)
	hunks := unifiedDiff(from, to, context)
	if maxLines > 0 {
		relevant := func(h diffHunk) bool {
			for _, line := range h.lines {
				if line[0] == ' ' {
					continue
				}
				for _, word := range keep {
					if word != "" && strings.Contains(line, word) {
						return true
					}
				}
			}
			return false
		}
		sorted := slices.Clone(hunks)
		slices.SortStableFunc(sorted, func(a, b diffHunk) int {
			switch ra, rb := relevant(a), relevant(b); {
			case ra && !rb:
				return -1
			case rb && !ra:
				return 1
			}
			return 0
		})
		var kept []diffHunk
		lines := 0
		for _, hunk := range sorted {
			if lines > 0 && lines+len(hunk.lines) > maxLines {
				break
			}
			if len(hunk.lines) > maxLines {
				hunk.lines = append(hunk.lines[:maxLines:maxLines], " …")
			}
			kept = append(kept, hunk)
			lines += len(hunk.lines)
		}
		slices.SortFunc(kept, func(a, b diffHunk) int { return a.fromLine - b.fromLine })
		if omitted := len(hunks) - len(kept); omitted > 0 {
			return formatUnifiedDiff("mjml 4.16.1", "gomjml", kept) + fmt.Sprintf("(%d more hunks; -diff.case prints them all)\n", omitted)
		}
		hunks = kept
	}
	return formatUnifiedDiff("mjml 4.16.1", "gomjml", hunks)
}

func prettyOutput(html, failure string) []string {
	if failure != "" {
		return []string{"(no output: " + strings.SplitN(failure, "\n", 2)[0] + ")"}
	}
	return prettyHTML(html)
}

// TestDifferentialCrashes renders edge documents, fuzzer documents beyond the compared corpus
// and damaged copies of them with gomjml alone, failing on any panic or hang.
func TestDifferentialCrashes(t *testing.T) {
	seeds := *crashSeeds
	if testing.Short() {
		seeds = min(seeds, 100)
	}
	type crash struct{ what, detail string }
	var mu sync.Mutex
	var crashes []crash
	var wg sync.WaitGroup
	work := make(chan uint64)
	for range runtime.GOMAXPROCS(0) {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for seed := range work {
				document := fuzzDocument(seed)
				inputs := map[string]string{fmt.Sprintf("fuzz seed %d", seed): document}
				r := rand.New(rand.NewPCG(seed, 1))
				for m := range 3 {
					data := make([]byte, 3*(1+r.IntN(4)))
					for i := range data {
						data[i] = byte(r.UintN(256))
					}
					inputs[fmt.Sprintf("fuzz seed %d, mutation %d (%x)", seed, m, data)] = mutate(document, data)
				}
				for what, input := range inputs {
					if _, _, detail := renderGuarded(input, *diffTimeout); detail != "" {
						mu.Lock()
						crashes = append(crashes, crash{what, detail})
						mu.Unlock()
					}
				}
			}
		}()
	}
	for name, document := range edgeDocuments() {
		if _, _, detail := renderGuarded(document, *diffTimeout); detail != "" {
			crashes = append(crashes, crash{"edge document " + name, detail})
		}
	}
	for seed := uint64(fuzzSeeds + 1); seed <= uint64(fuzzSeeds+seeds); seed++ {
		work <- seed
	}
	close(work)
	wg.Wait()
	slices.SortFunc(crashes, func(a, b crash) int { return strings.Compare(a.what, b.what) })
	bySignature := map[string][]string{}
	for _, c := range crashes {
		signature := crashSignature(c.detail)
		bySignature[signature] = append(bySignature[signature], c.what)
	}
	for _, signature := range slices.Sorted(maps.Keys(bySignature)) {
		t.Errorf("%s: %d inputs, first %s", signature, len(bySignature[signature]), bySignature[signature][0])
	}
}

// FuzzRender drives the grammar fuzzer from Go's fuzzing engine: the seed picks a document and
// the bytes damage it, as TestDifferentialCrashes does.
//
//	go test ./mjml -run '^$' -fuzz FuzzRender
func FuzzRender(f *testing.F) {
	f.Add(uint64(1), []byte{})
	f.Add(uint64(7), []byte{1, 128, 3})
	f.Add(uint64(42), []byte{0, 64, 10, 2, 200, 30})
	f.Fuzz(func(t *testing.T, seed uint64, data []byte) {
		input := mutate(fuzzDocument(seed), data)
		if _, _, crash := renderGuarded(input, *diffTimeout); crash != "" {
			t.Fatalf("%s\ninput:\n%s", crash, input)
		}
	})
}
